### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by guidoferreyra** [jbeyerstedt/kirby-kirbytag-download#4]
Sorry I don’t understand how to install it on kirby 3. Could you help me please.
Thanks

**Comment by jbeyerstedt** [comment]
To be honest, I haven't had the time to take a look at the release version of Kirby 3. This plugin was modified and tested in some Beta version. And I just realised, that the instructions in the readme are outdated. I'm sorry, that I don't have much time right now, but I'll try to test my plugins again on the weekend so I can update the instructions.

Could you please try to put all of these files in `/site/plugins/kirbytag-download/`. It _should_ work then.
(If you are using composer, please feel free to improve the support for that.)

**Comment by guidoferreyra** [comment]
Thanks It works now.
I was using "download" as the folder name and also I’m migrating from a kirby 2 site and I noticed that now is mandatory to add the `type:` to the download.
